version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
    ports:
      - 8080:8080
    networks:
      - wow-network

  client:
    build:
      context: .
      dockerfile: .docker/client/Dockerfile
    networks:
      - wow-network
    depends_on:
      - server

networks:
  wow-network:
    driver: bridge
