on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Lint codebase
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Run tests
        run: go test -count=1 ./...

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server
        uses: docker/build-push-action@v3
        with:
          file: .docker/server/Dockerfile
          tags: seth2810/wisdom-tcp-server:develop
          push: true

      - name: Build and push client
        uses: docker/build-push-action@v3
        with:
          file: .docker/client/Dockerfile
          tags: seth2810/wisdom-tcp-client:develop
          push: true
